### ISSUE TITLE
proportional loss ranking 

### ISSUE THREAD

**Issue by elgabbas** [cbig/zonation-core#16]
Hello,
I am using Zig4 to run some Zonation excercises, before trying it with my own data.

I wonder how to effectively change the settings for plotting "output weighted range size corrected richness" and "output proportional loss ranking". I tried to disallow the first by setting it to zero, while allowing the second by setting it to 1. In either cases no changes happened (wrscr map is always produced, but not the proportional loss ranking map).

I use these exact two lines in the settings file:
```
output weighted range size corrected richness = 0
output proportional loss ranking = 1
```
Thanks,
Ahmed

**Comment by koenkuipers** [comment]
I'm having exactly the same issue, using Zig4 on windows 10. Altering other settings in the "settings.dat" file  does result in changes in the zonation output, so the "settings.dat" file is being read properly. It just seems that adding an extra line with "output proportional loss ranking = 1" is not recognized. 

The simple settings file content:
```
[Settings]
removal rule = 2
warp factor = 200
edge removal = 1
output proportional loss ranking = 1
```

The output file "filename.run_unfo.info.txt" returns:

```
Output settings:
   Output weighted range size corrected richness map: yes
   Output proportional loss rank map: no
```

I wonder whether the command in the "settings.dat" file should just be different, or whether it is possible to make actual changes to the zig4 software so that the prop.rank raster is produced automatically again, like in the preceding zonation versions.

**Comment by PKullberg** [comment]
Hi elgabbas and koenkuipers.

Zonation is extremely picky about the spelling of stuff in the .dat and other settings files, and unfortunately not that verbose about things not being correct. To output the proportional loss rank map you should have exactly the following lines in the .dat file (pay attention to the capitals):

[Outputs]
output proportional loss rank map = 1

Hopefully this helps!

**Comment by PKullberg** [comment]
To clarify my answer a bit, both of you seem to have the  "output proportional loss rank map = 1" spelled correctly, but it should appear under the "[Outputs]" heading. The headings in the .dat file are important. In general only commands that area placed under correct headings are read properly.

**Comment by koenkuipers** [comment]
@PKullberg, this worked indeed! thank you very much. I just want to mention that it's not "output proportional loss rank map = 1", as you wrote above, but "output proportional loss ranking = 1". Adding the header "[Outputs]" fixed the issue. 

A simple settings.dat file should therefore for example look:

```
[Settings]
removal rule = 2
warp factor = 200
edge removal = 1

[Outputs]
output proportional loss ranking = 1
```

It's not mentioned in the _Zonation version 4 user manual_ that the header should be added; so if the developers are thinking of updating the software and/or use manual it would be great to add this!

**Comment by PKullberg** [comment]
@koenkuipers thanks for pointing out that wrong spelling in my answer.
The right one is, as you pointed out:
[Outputs]
output proportional loss ranking = 1
